# Generated by Django 2.2.2 on 2019-06-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='total_book_written',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three')], max_length=1),
        ),
    ]
